// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"fmt"
)

// ListApiKeys lists the API keys available to the authenticated user. Review each key's identifier, prefix, expiration, creation time, and last-seen time to manage existing credentials.
func ListApiKeys(ctx context.Context, clientConfig ClientConfig, opts ...RequestOption) (*ListApiKeysOutputBody, error) {

	resp, err := DoCfg[ListApiKeysOutputBody](ctx, &clientConfig, "GET", "/api/v1/apikey", &RequestOpts{
		OperationID: "ListApiKeys",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type CreateApiKeyParams struct {
	Expiration *string
}

// CreateApiKey creates a new API key. You can provide `expiration` as a date-time value or omit it if you do not want to specify an expiration. The response contains the generated key in `apiKey`.
//
// Parameters:
//
//	expiration: Optional `date-time`-formatted value serialized in the
//	`expiration` wire field.
func CreateApiKey(ctx context.Context, clientConfig ClientConfig, params CreateApiKeyParams, opts ...RequestOption) (*CreateApiKeyOutputBody, error) {
	expiration := params.Expiration

	if expiration != nil {
		if err := ValidateDateTime("expiration", *expiration); err != nil {
			return nil, err
		}
	}

	resp, err := DoCfg[CreateApiKeyOutputBody](ctx, &clientConfig, "POST", "/api/v1/apikey", &RequestOpts{
		Body: map[string]any{
			"expiration": expiration,
		},
		OperationID: "CreateApiKey",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type ExpireApiKeyParams struct {
	Id     *string
	Prefix *string
}

// ExpireApiKey expires an API key. Identify the key using `id`, `prefix`, or both, according to the key details available to you. The response confirms the operation with an empty object.
//
// Parameters:
//
//	id: Optional `uint64`-formatted value serialized in the `id` wire field.
//	prefix: Optional `string` value serialized in the `prefix` wire field.
func ExpireApiKey(ctx context.Context, clientConfig ClientConfig, params ExpireApiKeyParams, opts ...RequestOption) (*ExpireApiKeyOutputBody, error) {
	id := params.Id
	prefix := params.Prefix

	resp, err := DoCfg[ExpireApiKeyOutputBody](ctx, &clientConfig, "POST", "/api/v1/apikey/expire", &RequestOpts{
		Body: map[string]any{
			"id":     id,
			"prefix": prefix,
		},
		OperationID: "ExpireApiKey",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type DeleteApiKeyParams struct {
	Prefix string
	Id     *string
}

// DeleteApiKey deletes an API key selected by its prefix. You can also supply `id` as a uint64-formatted string to further identify the key. The response confirms the operation with an empty object.
func DeleteApiKey(ctx context.Context, clientConfig ClientConfig, params DeleteApiKeyParams, opts ...RequestOption) (*DeleteApiKeyOutputBody, error) {
	prefix := params.Prefix
	id := params.Id

	resp, err := DoCfg[DeleteApiKeyOutputBody](ctx, &clientConfig, "DELETE", fmt.Sprintf("/api/v1/apikey/%s", EncodePathSegment(prefix)), &RequestOpts{
		Query: map[string]any{
			"id": QueryValue{Value: id, Style: "form", Explode: false},
		},
		OperationID: "DeleteApiKey",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
