// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

type AuthApproveParams struct {
	AuthId *string
}

// AuthApprove approves a pending authentication session. Supply the session's `authId` to identify the request you want to approve. The response confirms the operation with an empty object.
//
// Parameters:
//
//	authId: Optional `string` value serialized in the `authId` wire field.
func AuthApprove(ctx context.Context, clientConfig ClientConfig, params AuthApproveParams, opts ...RequestOption) (*AuthApproveOutputBody, error) {
	authId := params.AuthId

	resp, err := DoCfg[AuthApproveOutputBody](ctx, &clientConfig, "POST", "/api/v1/auth/approve", &RequestOpts{
		Body: map[string]any{
			"authId": authId,
		},
		OperationID: "AuthApprove",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type AuthRegisterParams struct {
	AuthId *string
	User   *string
}

// AuthRegister registers a node through the authentication flow. Use `authId` to associate the registration with an authentication session and `user` to specify the user for the node. The response contains the registered node.
//
// Parameters:
//
//	authId: Optional `string` value serialized in the `authId` wire field.
//	user: Optional `string` value serialized in the `user` wire field.
func AuthRegister(ctx context.Context, clientConfig ClientConfig, params AuthRegisterParams, opts ...RequestOption) (*AuthRegisterOutputBody, error) {
	authId := params.AuthId
	user := params.User

	resp, err := DoCfg[AuthRegisterOutputBody](ctx, &clientConfig, "POST", "/api/v1/auth/register", &RequestOpts{
		Body: map[string]any{
			"authId": authId,
			"user":   user,
		},
		OperationID: "AuthRegister",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type AuthRejectParams struct {
	AuthId *string
}

// AuthReject rejects a pending authentication session. Supply the session's `authId` to identify the request you want to reject. The response confirms the operation with an empty object.
//
// Parameters:
//
//	authId: Optional `string` value serialized in the `authId` wire field.
func AuthReject(ctx context.Context, clientConfig ClientConfig, params AuthRejectParams, opts ...RequestOption) (*AuthRejectOutputBody, error) {
	authId := params.AuthId

	resp, err := DoCfg[AuthRejectOutputBody](ctx, &clientConfig, "POST", "/api/v1/auth/reject", &RequestOpts{
		Body: map[string]any{
			"authId": authId,
		},
		OperationID: "AuthReject",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
