// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

type ApiKeysNamespace struct {
	config ClientConfig
}

func NewApiKeysNamespace(config ClientConfig) *ApiKeysNamespace {
	return &ApiKeysNamespace{
		config: config,
	}
}

// List lists the API keys available to the authenticated user. Review each key's identifier, prefix, expiration, creation time, and last-seen time to manage existing credentials.
func (sdk *ApiKeysNamespace) List(ctx context.Context, opts ...RequestOption) (*ListApiKeysOutputBody, error) {
	return ListApiKeys(ctx, sdk.config, opts...)
}

// Create creates a new API key. You can provide `expiration` as a date-time value or omit it if you do not want to specify an expiration. The response contains the generated key in `apiKey`.
//
// Parameters:
//
//	expiration: Optional `date-time`-formatted value serialized in the
//	`expiration` wire field.
func (sdk *ApiKeysNamespace) Create(ctx context.Context, params CreateApiKeyParams, opts ...RequestOption) (*CreateApiKeyOutputBody, error) {
	return CreateApiKey(ctx, sdk.config, params, opts...)
}

// Expire expires an API key. Identify the key using `id`, `prefix`, or both, according to the key details available to you. The response confirms the operation with an empty object.
//
// Parameters:
//
//	id: Optional `uint64`-formatted value serialized in the `id` wire field.
//	prefix: Optional `string` value serialized in the `prefix` wire field.
func (sdk *ApiKeysNamespace) Expire(ctx context.Context, params ExpireApiKeyParams, opts ...RequestOption) (*ExpireApiKeyOutputBody, error) {
	return ExpireApiKey(ctx, sdk.config, params, opts...)
}

// Delete deletes an API key selected by its prefix. You can also supply `id` as a uint64-formatted string to further identify the key. The response confirms the operation with an empty object.
func (sdk *ApiKeysNamespace) Delete(ctx context.Context, params DeleteApiKeyParams, opts ...RequestOption) (*DeleteApiKeyOutputBody, error) {
	return DeleteApiKey(ctx, sdk.config, params, opts...)
}

type AuthNamespace struct {
	config ClientConfig
}

func NewAuthNamespace(config ClientConfig) *AuthNamespace {
	return &AuthNamespace{
		config: config,
	}
}

// Approve approves a pending authentication session. Supply the session's `authId` to identify the request you want to approve. The response confirms the operation with an empty object.
//
// Parameters:
//
//	authId: Optional `string` value serialized in the `authId` wire field.
func (sdk *AuthNamespace) Approve(ctx context.Context, params AuthApproveParams, opts ...RequestOption) (*AuthApproveOutputBody, error) {
	return AuthApprove(ctx, sdk.config, params, opts...)
}

// Register registers a node through the authentication flow. Use `authId` to associate the registration with an authentication session and `user` to specify the user for the node. The response contains the registered node.
//
// Parameters:
//
//	authId: Optional `string` value serialized in the `authId` wire field.
//	user: Optional `string` value serialized in the `user` wire field.
func (sdk *AuthNamespace) Register(ctx context.Context, params AuthRegisterParams, opts ...RequestOption) (*AuthRegisterOutputBody, error) {
	return AuthRegister(ctx, sdk.config, params, opts...)
}

// Reject rejects a pending authentication session. Supply the session's `authId` to identify the request you want to reject. The response confirms the operation with an empty object.
//
// Parameters:
//
//	authId: Optional `string` value serialized in the `authId` wire field.
func (sdk *AuthNamespace) Reject(ctx context.Context, params AuthRejectParams, opts ...RequestOption) (*AuthRejectOutputBody, error) {
	return AuthReject(ctx, sdk.config, params, opts...)
}

type NodesNamespace struct {
	config ClientConfig
}

func NewNodesNamespace(config ClientConfig) *NodesNamespace {
	return &NodesNamespace{
		config: config,
	}
}

// DebugCreate creates a node for debugging purposes. Provide `name` and `user` to describe the node, and use `key` or `routes` when those values are needed for the test setup. The response contains the created node.
//
// Parameters:
//
//	key: Optional `string` value serialized in the `key` wire field.
//	name: Optional `string` value serialized in the `name` wire field.
//	routes: Optional array value serialized in the `routes` wire field.
//	user: Optional `string` value serialized in the `user` wire field.
func (sdk *NodesNamespace) DebugCreate(ctx context.Context, params DebugCreateNodeParams, opts ...RequestOption) (*NodeOutputBody, error) {
	return DebugCreateNode(ctx, sdk.config, params, opts...)
}

// List lists nodes managed by the service. Supply `user` to filter the results to nodes associated with that user; omit it to list nodes without a user filter.
func (sdk *NodesNamespace) List(ctx context.Context, params ListNodesParams, opts ...RequestOption) (*ListNodesOutputBody, error) {
	return ListNodes(ctx, sdk.config, params, opts...)
}

// BackfillIps backfills IP addresses for registered nodes. Use the `confirmed` query parameter to indicate whether to confirm the operation, and review the returned `changes` list to see what was updated.
func (sdk *NodesNamespace) BackfillIps(ctx context.Context, params BackfillNodeIPsParams, opts ...RequestOption) (*BackfillNodeIPsOutputBody, error) {
	return BackfillNodeIPs(ctx, sdk.config, params, opts...)
}

// Register registers a node and returns its node record. Use `user` to associate the node with a user and `key` to provide a registration key when needed.
func (sdk *NodesNamespace) Register(ctx context.Context, params RegisterNodeParams, opts ...RequestOption) (*NodeOutputBody, error) {
	return RegisterNode(ctx, sdk.config, params, opts...)
}

// Delete deletes a node identified by its ID. Supply `nodeId` as an unsigned 64-bit integer value to identify the node to remove.
func (sdk *NodesNamespace) Delete(ctx context.Context, params DeleteNodeParams, opts ...RequestOption) (*DeleteNodeOutputBody, error) {
	return DeleteNode(ctx, sdk.config, params, opts...)
}

// Get retrieves a node by its identifier. Supply `nodeId` as an unsigned 64-bit integer value to identify the node.
func (sdk *NodesNamespace) Get(ctx context.Context, params GetNodeParams, opts ...RequestOption) (*NodeOutputBody, error) {
	return GetNode(ctx, sdk.config, params, opts...)
}

// SetApprovedRoutes updates the approved routes for a node. Send the route values in the `routes` array to set which routes are approved for that node.
//
// Parameters:
//
//	routes: Optional array value serialized in the `routes` wire field.
func (sdk *NodesNamespace) SetApprovedRoutes(ctx context.Context, params SetApprovedRoutesParams, opts ...RequestOption) (*NodeOutputBody, error) {
	return SetApprovedRoutes(ctx, sdk.config, params, opts...)
}

// Expire updates the expiry settings for a node. Supply `expiry` as an ISO 8601 date-time or use `disableExpiry` to specify whether expiry is disabled.
//
// Parameters:
//
//	disableExpiry: Optional `boolean` value serialized in the `disableExpiry`
//	wire field.
//	expiry: Optional `date-time`-formatted value serialized in the `expiry` wire
//	field.
func (sdk *NodesNamespace) Expire(ctx context.Context, params ExpireNodeParams, opts ...RequestOption) (*NodeOutputBody, error) {
	return ExpireNode(ctx, sdk.config, params, opts...)
}

// Rename renames a node by setting its new name. Supply the node identifier and the new name in the path.
func (sdk *NodesNamespace) Rename(ctx context.Context, params RenameNodeParams, opts ...RequestOption) (*NodeOutputBody, error) {
	return RenameNode(ctx, sdk.config, params, opts...)
}

// SetTags sets the tags for a node. Send the tags as an array of strings in the request body.
//
// Parameters:
//
//	tags: Optional array value serialized in the `tags` wire field.
func (sdk *NodesNamespace) SetTags(ctx context.Context, params SetTagsParams, opts ...RequestOption) (*NodeOutputBody, error) {
	return SetTags(ctx, sdk.config, params, opts...)
}

type HealthNamespace struct {
	config ClientConfig
}

func NewHealthNamespace(config ClientConfig) *HealthNamespace {
	return &HealthNamespace{
		config: config,
	}
}

// Health reports the server's health, including database connectivity. Read `databaseConnectivity` to determine whether the database connection is available.
//
// Reports server health, including database connectivity.
func (sdk *HealthNamespace) Health(ctx context.Context, opts ...RequestOption) (*HealthResponseBody, error) {
	return Health(ctx, sdk.config, opts...)
}

type PolicyNamespace struct {
	config ClientConfig
}

func NewPolicyNamespace(config ClientConfig) *PolicyNamespace {
	return &PolicyNamespace{
		config: config,
	}
}

// Get retrieves the current policy. The response includes the policy text and the time it was last updated.
func (sdk *PolicyNamespace) Get(ctx context.Context, opts ...RequestOption) (*PolicyResponseBody, error) {
	return GetPolicy(ctx, sdk.config, opts...)
}

// Set replaces the current policy with the policy value supplied in the request body. Include the policy text in `policy`; the response provides the saved policy and its update time.
//
// Parameters:
//
//	policy: Optional `string` value serialized in the `policy` wire field.
func (sdk *PolicyNamespace) Set(ctx context.Context, params SetPolicyParams, opts ...RequestOption) (*PolicyResponseBody, error) {
	return SetPolicy(ctx, sdk.config, params, opts...)
}

// Check validates a policy against the server's live users and nodes without saving it. Provide `policy` as a string when included; the request body is required.
//
// Validates the given policy against the server's live users and nodes without persisting it.
//
// Parameters:
//
//	policy: Optional `string` value serialized in the `policy` wire field.
func (sdk *PolicyNamespace) Check(ctx context.Context, params CheckPolicyParams, opts ...RequestOption) (*CheckPolicyOutputBody, error) {
	return CheckPolicy(ctx, sdk.config, params, opts...)
}

type PreAuthKeysNamespace struct {
	config ClientConfig
}

func NewPreAuthKeysNamespace(config ClientConfig) *PreAuthKeysNamespace {
	return &PreAuthKeysNamespace{
		config: config,
	}
}

// Delete deletes a pre-auth key. Use the optional `id` query parameter to identify the key to delete; provide it as a uint64-formatted string when supplied.
func (sdk *PreAuthKeysNamespace) Delete(ctx context.Context, params DeletePreAuthKeyParams, opts ...RequestOption) (*DeletePreAuthKeyOutputBody, error) {
	return DeletePreAuthKey(ctx, sdk.config, params, opts...)
}

// List lists the pre-auth keys configured on the server. Use this operation to retrieve each key's user, key value, expiration, usage state, and ACL tags.
func (sdk *PreAuthKeysNamespace) List(ctx context.Context, opts ...RequestOption) (*ListPreAuthKeysOutputBody, error) {
	return ListPreAuthKeys(ctx, sdk.config, opts...)
}

// Create creates a pre-auth key for a user. Configure the key with fields such as `user`, `expiration`, `reusable`, `ephemeral`, and `aclTags`; `user` is a uint64-formatted string and `expiration` is a date-time.
//
// Parameters:
//
//	aclTags: Optional array value serialized in the `aclTags` wire field.
//	ephemeral: Optional `boolean` value serialized in the `ephemeral` wire
//	field.
//	expiration: Optional `date-time`-formatted value serialized in the
//	`expiration` wire field.
//	reusable: Optional `boolean` value serialized in the `reusable` wire field.
//	user: Optional `uint64`-formatted value serialized in the `user` wire field.
func (sdk *PreAuthKeysNamespace) Create(ctx context.Context, params CreatePreAuthKeyParams, opts ...RequestOption) (*PreAuthKeyOutputBody, error) {
	return CreatePreAuthKey(ctx, sdk.config, params, opts...)
}

// Expire expires a pre-auth key. Supply its identifier in the `id` field as a uint64-formatted string when specifying which key to expire.
//
// Parameters:
//
//	id: Optional `uint64`-formatted value serialized in the `id` wire field.
func (sdk *PreAuthKeysNamespace) Expire(ctx context.Context, params ExpirePreAuthKeyParams, opts ...RequestOption) (*ExpirePreAuthKeyOutputBody, error) {
	return ExpirePreAuthKey(ctx, sdk.config, params, opts...)
}

type UsersNamespace struct {
	config ClientConfig
}

func NewUsersNamespace(config ClientConfig) *UsersNamespace {
	return &UsersNamespace{
		config: config,
	}
}

// List lists users, with optional filters for user identifier, name, or email. Supply `id` as a uint64-formatted string when filtering by identifier; `name` and `email` are string filters.
func (sdk *UsersNamespace) List(ctx context.Context, params ListUsersParams, opts ...RequestOption) (*ListUsersOutputBody, error) {
	return ListUsers(ctx, sdk.config, params, opts...)
}

// Create creates a user record. You can provide `name`, `displayName`, `email`, and `pictureUrl`; all defined fields are strings and none is marked as required.
//
// Parameters:
//
//	displayName: Optional `string` value serialized in the `displayName` wire
//	field.
//	email: Optional `string` value serialized in the `email` wire field.
//	name: Optional `string` value serialized in the `name` wire field.
//	pictureUrl: Optional `string` value serialized in the `pictureUrl` wire
//	field.
func (sdk *UsersNamespace) Create(ctx context.Context, params CreateUserParams, opts ...RequestOption) (*UserOutputBody, error) {
	return CreateUser(ctx, sdk.config, params, opts...)
}

// Delete deletes a user by identifier. Provide the user's `id` as a uint64-formatted string in the path.
func (sdk *UsersNamespace) Delete(ctx context.Context, params DeleteUserParams, opts ...RequestOption) (*DeleteUserOutputBody, error) {
	return DeleteUser(ctx, sdk.config, params, opts...)
}

// Rename renames a user by changing the name associated with the specified identifier. Provide `oldId` as a uint64-formatted string and `newName` as a string in the path.
func (sdk *UsersNamespace) Rename(ctx context.Context, params RenameUserParams, opts ...RequestOption) (*UserOutputBody, error) {
	return RenameUser(ctx, sdk.config, params, opts...)
}

type Headscale struct {
	ApiKeys     *ApiKeysNamespace
	Auth        *AuthNamespace
	Nodes       *NodesNamespace
	Health      *HealthNamespace
	Policy      *PolicyNamespace
	PreAuthKeys *PreAuthKeysNamespace
	Users       *UsersNamespace
}

func NewHeadscale(config ClientConfig) *Headscale {
	return &Headscale{
		ApiKeys:     NewApiKeysNamespace(config),
		Auth:        NewAuthNamespace(config),
		Nodes:       NewNodesNamespace(config),
		Health:      NewHealthNamespace(config),
		Policy:      NewPolicyNamespace(config),
		PreAuthKeys: NewPreAuthKeysNamespace(config),
		Users:       NewUsersNamespace(config),
	}
}
