// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// Health reports the server's health, including database connectivity. Read `databaseConnectivity` to determine whether the database connection is available.
//
// Reports server health, including database connectivity.
func Health(ctx context.Context, clientConfig ClientConfig, opts ...RequestOption) (*HealthResponseBody, error) {

	resp, err := DoCfg[HealthResponseBody](ctx, &clientConfig, "GET", "/api/v1/health", &RequestOpts{
		OperationID: "Health",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
