// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"bytes"
	"encoding/json"
)

// CreatePreAuthKeyRequestBody Typed representation of the `CreatePreAuthKeyRequestBody` API schema.
type CreatePreAuthKeyRequestBody struct {
	// AclTags Optional array value serialized in the `aclTags` wire field.
	AclTags *NullableValue[[]string] `json:"aclTags,omitempty"`
	// Ephemeral Optional `boolean` value serialized in the `ephemeral` wire field.
	Ephemeral *bool `json:"ephemeral,omitempty"`
	// Expiration Optional `date-time`-formatted value serialized in the `expiration` wire field.
	Expiration *string `json:"expiration,omitempty"`
	// Reusable Optional `boolean` value serialized in the `reusable` wire field.
	Reusable *bool `json:"reusable,omitempty"`
	// User Optional `uint64`-formatted value serialized in the `user` wire field.
	User *string `json:"user,omitempty"`
}

func (value *CreatePreAuthKeyRequestBody) UnmarshalJSON(data []byte) error {
	type CreatePreAuthKeyRequestBodyAlias CreatePreAuthKeyRequestBody
	var decoded CreatePreAuthKeyRequestBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = CreatePreAuthKeyRequestBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if value.Expiration != nil {
		if err := ValidateDateTime("expiration", *value.Expiration); err != nil {
			return err
		}
	}
	if raw, ok := rawFields["aclTags"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.AclTags = &NullableValue[[]string]{}
	}
	return nil
}

// NewCreatePreAuthKeyRequestBody returns a validated CreatePreAuthKeyRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewCreatePreAuthKeyRequestBody(fields CreatePreAuthKeyRequestBody) (*CreatePreAuthKeyRequestBody, error) {
	return ConstructModel(fields)
}

// DeletePreAuthKeyOutputBody Typed representation of the `DeletePreAuthKeyOutputBody` API schema.
type DeletePreAuthKeyOutputBody struct {
}

// ExpirePreAuthKeyOutputBody Typed representation of the `ExpirePreAuthKeyOutputBody` API schema.
type ExpirePreAuthKeyOutputBody struct {
}

// ExpirePreAuthKeyRequestBody Typed representation of the `ExpirePreAuthKeyRequestBody` API schema.
type ExpirePreAuthKeyRequestBody struct {
	// Id Optional `uint64`-formatted value serialized in the `id` wire field.
	Id *string `json:"id,omitempty"`
}

// NewExpirePreAuthKeyRequestBody returns a validated ExpirePreAuthKeyRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewExpirePreAuthKeyRequestBody(fields ExpirePreAuthKeyRequestBody) (*ExpirePreAuthKeyRequestBody, error) {
	return ConstructModel(fields)
}

// ListPreAuthKeysOutputBody Typed representation of the `ListPreAuthKeysOutputBody` API schema.
type ListPreAuthKeysOutputBody struct {
	// PreAuthKeys Required array value serialized in the `preAuthKeys` wire field.
	PreAuthKeys []PreAuthKey `json:"preAuthKeys"`
}

func (value *ListPreAuthKeysOutputBody) UnmarshalJSON(data []byte) error {
	type ListPreAuthKeysOutputBodyAlias ListPreAuthKeysOutputBody
	var decoded ListPreAuthKeysOutputBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ListPreAuthKeysOutputBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"preAuthKeys"}); err != nil {
		return err
	}
	return nil
}

// NewListPreAuthKeysOutputBody returns a validated ListPreAuthKeysOutputBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewListPreAuthKeysOutputBody(fields ListPreAuthKeysOutputBody) (*ListPreAuthKeysOutputBody, error) {
	return ConstructModel(fields)
}

// PreAuthKey Typed representation of the `PreAuthKey` API schema.
type PreAuthKey struct {
	// AclTags Required array value serialized in the `aclTags` wire field.
	AclTags []string `json:"aclTags"`
	// CreatedAt Required `date-time`-formatted value serialized in the `createdAt` wire field.
	CreatedAt string `json:"createdAt"`
	// Ephemeral Required `boolean` value serialized in the `ephemeral` wire field.
	Ephemeral bool `json:"ephemeral"`
	// Expiration Required `date-time`-formatted value serialized in the `expiration` wire field.
	Expiration string `json:"expiration"`
	// Id Required `uint64`-formatted value serialized in the `id` wire field.
	Id string `json:"id"`
	// Key Required `string` value serialized in the `key` wire field.
	Key string `json:"key"`
	// Reusable Required `boolean` value serialized in the `reusable` wire field.
	Reusable bool `json:"reusable"`
	// Used Required `boolean` value serialized in the `used` wire field.
	Used bool `json:"used"`
	// User Required object value serialized in the `user` wire field.
	User User `json:"user"`
}

func (value *PreAuthKey) UnmarshalJSON(data []byte) error {
	type PreAuthKeyAlias PreAuthKey
	var decoded PreAuthKeyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = PreAuthKey(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"user", "id", "key", "reusable", "ephemeral", "used", "expiration", "createdAt", "aclTags"}); err != nil {
		return err
	}
	if err := ValidateDateTime("createdAt", value.CreatedAt); err != nil {
		return err
	}
	if err := ValidateDateTime("expiration", value.Expiration); err != nil {
		return err
	}
	return nil
}

// NewPreAuthKey returns a validated PreAuthKey built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewPreAuthKey(fields PreAuthKey) (*PreAuthKey, error) {
	return ConstructModel(fields)
}

// PreAuthKeyOutputBody Typed representation of the `PreAuthKeyOutputBody` API schema.
type PreAuthKeyOutputBody struct {
	// PreAuthKey Required object value serialized in the `preAuthKey` wire field.
	PreAuthKey PreAuthKey `json:"preAuthKey"`
}

func (value *PreAuthKeyOutputBody) UnmarshalJSON(data []byte) error {
	type PreAuthKeyOutputBodyAlias PreAuthKeyOutputBody
	var decoded PreAuthKeyOutputBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = PreAuthKeyOutputBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"preAuthKey"}); err != nil {
		return err
	}
	return nil
}

// NewPreAuthKeyOutputBody returns a validated PreAuthKeyOutputBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewPreAuthKeyOutputBody(fields PreAuthKeyOutputBody) (*PreAuthKeyOutputBody, error) {
	return ConstructModel(fields)
}
