// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// CheckPolicyOutputBody Typed representation of the `CheckPolicyOutputBody` API schema.
type CheckPolicyOutputBody struct {
}

// PolicyRequestBody Typed representation of the `PolicyRequestBody` API schema.
type PolicyRequestBody struct {
	// Policy Optional `string` value serialized in the `policy` wire field.
	Policy *string `json:"policy,omitempty"`
}

// NewPolicyRequestBody returns a validated PolicyRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewPolicyRequestBody(fields PolicyRequestBody) (*PolicyRequestBody, error) {
	return ConstructModel(fields)
}

// PolicyResponseBody Typed representation of the `PolicyResponseBody` API schema.
type PolicyResponseBody struct {
	// Policy Required `string` value serialized in the `policy` wire field.
	Policy string `json:"policy"`
	// UpdatedAt Required `date-time`-formatted value serialized in the `updatedAt` wire field.
	UpdatedAt string `json:"updatedAt"`
}

func (value *PolicyResponseBody) UnmarshalJSON(data []byte) error {
	type PolicyResponseBodyAlias PolicyResponseBody
	var decoded PolicyResponseBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = PolicyResponseBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"policy", "updatedAt"}); err != nil {
		return err
	}
	if err := ValidateDateTime("updatedAt", value.UpdatedAt); err != nil {
		return err
	}
	return nil
}

// NewPolicyResponseBody returns a validated PolicyResponseBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewPolicyResponseBody(fields PolicyResponseBody) (*PolicyResponseBody, error) {
	return ConstructModel(fields)
}
