// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// CreateUserRequestBody Typed representation of the `CreateUserRequestBody` API schema.
type CreateUserRequestBody struct {
	// DisplayName Optional `string` value serialized in the `displayName` wire field.
	DisplayName *string `json:"displayName,omitempty"`
	// Email Optional `string` value serialized in the `email` wire field.
	Email *string `json:"email,omitempty"`
	// Name Optional `string` value serialized in the `name` wire field.
	Name *string `json:"name,omitempty"`
	// PictureUrl Optional `string` value serialized in the `pictureUrl` wire field.
	PictureUrl *string `json:"pictureUrl,omitempty"`
}

// NewCreateUserRequestBody returns a validated CreateUserRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewCreateUserRequestBody(fields CreateUserRequestBody) (*CreateUserRequestBody, error) {
	return ConstructModel(fields)
}

// DeleteUserOutputBody Typed representation of the `DeleteUserOutputBody` API schema.
type DeleteUserOutputBody struct {
}

// ListUsersOutputBody Typed representation of the `ListUsersOutputBody` API schema.
type ListUsersOutputBody struct {
	// Users Required array value serialized in the `users` wire field.
	Users []User `json:"users"`
}

func (value *ListUsersOutputBody) UnmarshalJSON(data []byte) error {
	type ListUsersOutputBodyAlias ListUsersOutputBody
	var decoded ListUsersOutputBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ListUsersOutputBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"users"}); err != nil {
		return err
	}
	return nil
}

// NewListUsersOutputBody returns a validated ListUsersOutputBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewListUsersOutputBody(fields ListUsersOutputBody) (*ListUsersOutputBody, error) {
	return ConstructModel(fields)
}

// UserOutputBody Typed representation of the `UserOutputBody` API schema.
type UserOutputBody struct {
	// User Required object value serialized in the `user` wire field.
	User User `json:"user"`
}

func (value *UserOutputBody) UnmarshalJSON(data []byte) error {
	type UserOutputBodyAlias UserOutputBody
	var decoded UserOutputBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = UserOutputBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"user"}); err != nil {
		return err
	}
	return nil
}

// NewUserOutputBody returns a validated UserOutputBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewUserOutputBody(fields UserOutputBody) (*UserOutputBody, error) {
	return ConstructModel(fields)
}
