// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"bytes"
	"encoding/json"
)

// BackfillNodeIPsOutputBody Typed representation of the `BackfillNodeIPsOutputBody` API schema.
type BackfillNodeIPsOutputBody struct {
	// Changes Required array value serialized in the `changes` wire field.
	Changes []string `json:"changes"`
}

func (value *BackfillNodeIPsOutputBody) UnmarshalJSON(data []byte) error {
	type BackfillNodeIPsOutputBodyAlias BackfillNodeIPsOutputBody
	var decoded BackfillNodeIPsOutputBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = BackfillNodeIPsOutputBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"changes"}); err != nil {
		return err
	}
	return nil
}

// NewBackfillNodeIPsOutputBody returns a validated BackfillNodeIPsOutputBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewBackfillNodeIPsOutputBody(fields BackfillNodeIPsOutputBody) (*BackfillNodeIPsOutputBody, error) {
	return ConstructModel(fields)
}

// DebugCreateNodeRequestBody Typed representation of the `DebugCreateNodeRequestBody` API schema.
type DebugCreateNodeRequestBody struct {
	// Key Optional `string` value serialized in the `key` wire field.
	Key *string `json:"key,omitempty"`
	// Name Optional `string` value serialized in the `name` wire field.
	Name *string `json:"name,omitempty"`
	// Routes Optional array value serialized in the `routes` wire field.
	Routes *NullableValue[[]string] `json:"routes,omitempty"`
	// User Optional `string` value serialized in the `user` wire field.
	User *string `json:"user,omitempty"`
}

func (value *DebugCreateNodeRequestBody) UnmarshalJSON(data []byte) error {
	type DebugCreateNodeRequestBodyAlias DebugCreateNodeRequestBody
	var decoded DebugCreateNodeRequestBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = DebugCreateNodeRequestBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if raw, ok := rawFields["routes"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Routes = &NullableValue[[]string]{}
	}
	return nil
}

// NewDebugCreateNodeRequestBody returns a validated DebugCreateNodeRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewDebugCreateNodeRequestBody(fields DebugCreateNodeRequestBody) (*DebugCreateNodeRequestBody, error) {
	return ConstructModel(fields)
}

// DeleteNodeOutputBody Typed representation of the `DeleteNodeOutputBody` API schema.
type DeleteNodeOutputBody struct {
}

// ExpireNodeRequestBody Typed representation of the `ExpireNodeRequestBody` API schema.
type ExpireNodeRequestBody struct {
	// DisableExpiry Optional `boolean` value serialized in the `disableExpiry` wire field.
	DisableExpiry *bool `json:"disableExpiry,omitempty"`
	// Expiry Optional `date-time`-formatted value serialized in the `expiry` wire field.
	Expiry *string `json:"expiry,omitempty"`
}

func (value *ExpireNodeRequestBody) UnmarshalJSON(data []byte) error {
	type ExpireNodeRequestBodyAlias ExpireNodeRequestBody
	var decoded ExpireNodeRequestBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ExpireNodeRequestBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if value.Expiry != nil {
		if err := ValidateDateTime("expiry", *value.Expiry); err != nil {
			return err
		}
	}
	return nil
}

// NewExpireNodeRequestBody returns a validated ExpireNodeRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewExpireNodeRequestBody(fields ExpireNodeRequestBody) (*ExpireNodeRequestBody, error) {
	return ConstructModel(fields)
}

// ListNodesOutputBody Typed representation of the `ListNodesOutputBody` API schema.
type ListNodesOutputBody struct {
	// Nodes Required array value serialized in the `nodes` wire field.
	Nodes []Node `json:"nodes"`
}

func (value *ListNodesOutputBody) UnmarshalJSON(data []byte) error {
	type ListNodesOutputBodyAlias ListNodesOutputBody
	var decoded ListNodesOutputBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ListNodesOutputBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"nodes"}); err != nil {
		return err
	}
	return nil
}

// NewListNodesOutputBody returns a validated ListNodesOutputBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewListNodesOutputBody(fields ListNodesOutputBody) (*ListNodesOutputBody, error) {
	return ConstructModel(fields)
}

// NodeOutputBody Typed representation of the `NodeOutputBody` API schema.
type NodeOutputBody struct {
	// Node Required object value serialized in the `node` wire field.
	Node Node `json:"node"`
}

func (value *NodeOutputBody) UnmarshalJSON(data []byte) error {
	type NodeOutputBodyAlias NodeOutputBody
	var decoded NodeOutputBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = NodeOutputBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"node"}); err != nil {
		return err
	}
	return nil
}

// NewNodeOutputBody returns a validated NodeOutputBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewNodeOutputBody(fields NodeOutputBody) (*NodeOutputBody, error) {
	return ConstructModel(fields)
}

// SetApprovedRoutesRequestBody Typed representation of the `SetApprovedRoutesRequestBody` API schema.
type SetApprovedRoutesRequestBody struct {
	// Routes Optional array value serialized in the `routes` wire field.
	Routes *NullableValue[[]string] `json:"routes,omitempty"`
}

func (value *SetApprovedRoutesRequestBody) UnmarshalJSON(data []byte) error {
	type SetApprovedRoutesRequestBodyAlias SetApprovedRoutesRequestBody
	var decoded SetApprovedRoutesRequestBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = SetApprovedRoutesRequestBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if raw, ok := rawFields["routes"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Routes = &NullableValue[[]string]{}
	}
	return nil
}

// NewSetApprovedRoutesRequestBody returns a validated SetApprovedRoutesRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewSetApprovedRoutesRequestBody(fields SetApprovedRoutesRequestBody) (*SetApprovedRoutesRequestBody, error) {
	return ConstructModel(fields)
}

// SetTagsRequestBody Typed representation of the `SetTagsRequestBody` API schema.
type SetTagsRequestBody struct {
	// Tags Optional array value serialized in the `tags` wire field.
	Tags *NullableValue[[]string] `json:"tags,omitempty"`
}

func (value *SetTagsRequestBody) UnmarshalJSON(data []byte) error {
	type SetTagsRequestBodyAlias SetTagsRequestBody
	var decoded SetTagsRequestBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = SetTagsRequestBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if raw, ok := rawFields["tags"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Tags = &NullableValue[[]string]{}
	}
	return nil
}

// NewSetTagsRequestBody returns a validated SetTagsRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewSetTagsRequestBody(fields SetTagsRequestBody) (*SetTagsRequestBody, error) {
	return ConstructModel(fields)
}
