// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// ApiKey Typed representation of the `ApiKey` API schema.
type ApiKey struct {
	// CreatedAt Required `date-time`-formatted value serialized in the `createdAt` wire field.
	CreatedAt NullableValue[string] `json:"createdAt"`
	// Expiration Required `date-time`-formatted value serialized in the `expiration` wire field.
	Expiration NullableValue[string] `json:"expiration"`
	// Id Required `uint64`-formatted value serialized in the `id` wire field.
	Id string `json:"id"`
	// LastSeen Required `date-time`-formatted value serialized in the `lastSeen` wire field.
	LastSeen NullableValue[string] `json:"lastSeen"`
	// Prefix Required `string` value serialized in the `prefix` wire field.
	Prefix string `json:"prefix"`
}

func (value *ApiKey) UnmarshalJSON(data []byte) error {
	type ApiKeyAlias ApiKey
	var decoded ApiKeyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ApiKey(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id", "prefix", "expiration", "createdAt", "lastSeen"}); err != nil {
		return err
	}
	return nil
}

// NewApiKey returns a validated ApiKey built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewApiKey(fields ApiKey) (*ApiKey, error) {
	return ConstructModel(fields)
}

// CreateApiKeyOutputBody Typed representation of the `CreateApiKeyOutputBody` API schema.
type CreateApiKeyOutputBody struct {
	// ApiKey Required `string` value serialized in the `apiKey` wire field.
	ApiKey string `json:"apiKey"`
}

func (value *CreateApiKeyOutputBody) UnmarshalJSON(data []byte) error {
	type CreateApiKeyOutputBodyAlias CreateApiKeyOutputBody
	var decoded CreateApiKeyOutputBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = CreateApiKeyOutputBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"apiKey"}); err != nil {
		return err
	}
	return nil
}

// NewCreateApiKeyOutputBody returns a validated CreateApiKeyOutputBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewCreateApiKeyOutputBody(fields CreateApiKeyOutputBody) (*CreateApiKeyOutputBody, error) {
	return ConstructModel(fields)
}

// CreateApiKeyRequestBody Typed representation of the `CreateApiKeyRequestBody` API schema.
type CreateApiKeyRequestBody struct {
	// Expiration Optional `date-time`-formatted value serialized in the `expiration` wire field.
	Expiration *string `json:"expiration,omitempty"`
}

func (value *CreateApiKeyRequestBody) UnmarshalJSON(data []byte) error {
	type CreateApiKeyRequestBodyAlias CreateApiKeyRequestBody
	var decoded CreateApiKeyRequestBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = CreateApiKeyRequestBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if value.Expiration != nil {
		if err := ValidateDateTime("expiration", *value.Expiration); err != nil {
			return err
		}
	}
	return nil
}

// NewCreateApiKeyRequestBody returns a validated CreateApiKeyRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewCreateApiKeyRequestBody(fields CreateApiKeyRequestBody) (*CreateApiKeyRequestBody, error) {
	return ConstructModel(fields)
}

// DeleteApiKeyOutputBody Typed representation of the `DeleteApiKeyOutputBody` API schema.
type DeleteApiKeyOutputBody struct {
}

// ExpireApiKeyOutputBody Typed representation of the `ExpireApiKeyOutputBody` API schema.
type ExpireApiKeyOutputBody struct {
}

// ExpireApiKeyRequestBody Typed representation of the `ExpireApiKeyRequestBody` API schema.
type ExpireApiKeyRequestBody struct {
	// Id Optional `uint64`-formatted value serialized in the `id` wire field.
	Id *string `json:"id,omitempty"`
	// Prefix Optional `string` value serialized in the `prefix` wire field.
	Prefix *string `json:"prefix,omitempty"`
}

// NewExpireApiKeyRequestBody returns a validated ExpireApiKeyRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewExpireApiKeyRequestBody(fields ExpireApiKeyRequestBody) (*ExpireApiKeyRequestBody, error) {
	return ConstructModel(fields)
}

// ListApiKeysOutputBody Typed representation of the `ListApiKeysOutputBody` API schema.
type ListApiKeysOutputBody struct {
	// ApiKeys Required array value serialized in the `apiKeys` wire field.
	ApiKeys []ApiKey `json:"apiKeys"`
}

func (value *ListApiKeysOutputBody) UnmarshalJSON(data []byte) error {
	type ListApiKeysOutputBodyAlias ListApiKeysOutputBody
	var decoded ListApiKeysOutputBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ListApiKeysOutputBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"apiKeys"}); err != nil {
		return err
	}
	return nil
}

// NewListApiKeysOutputBody returns a validated ListApiKeysOutputBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewListApiKeysOutputBody(fields ListApiKeysOutputBody) (*ListApiKeysOutputBody, error) {
	return ConstructModel(fields)
}
