// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// HealthResponseBody Typed representation of the `HealthResponseBody` API schema.
type HealthResponseBody struct {
	// DatabaseConnectivity Required `boolean` value serialized in the `databaseConnectivity` wire field.
	DatabaseConnectivity bool `json:"databaseConnectivity"`
}

func (value *HealthResponseBody) UnmarshalJSON(data []byte) error {
	type HealthResponseBodyAlias HealthResponseBody
	var decoded HealthResponseBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = HealthResponseBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"databaseConnectivity"}); err != nil {
		return err
	}
	return nil
}

// NewHealthResponseBody returns a validated HealthResponseBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewHealthResponseBody(fields HealthResponseBody) (*HealthResponseBody, error) {
	return ConstructModel(fields)
}
