// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// AuthApproveOutputBody Typed representation of the `AuthApproveOutputBody` API schema.
type AuthApproveOutputBody struct {
}

// AuthApproveRequestBody Typed representation of the `AuthApproveRequestBody` API schema.
type AuthApproveRequestBody struct {
	// AuthId Optional `string` value serialized in the `authId` wire field.
	AuthId *string `json:"authId,omitempty"`
}

// NewAuthApproveRequestBody returns a validated AuthApproveRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAuthApproveRequestBody(fields AuthApproveRequestBody) (*AuthApproveRequestBody, error) {
	return ConstructModel(fields)
}

// AuthRegisterOutputBody Typed representation of the `AuthRegisterOutputBody` API schema.
type AuthRegisterOutputBody struct {
	// Node Required object value serialized in the `node` wire field.
	Node Node `json:"node"`
}

func (value *AuthRegisterOutputBody) UnmarshalJSON(data []byte) error {
	type AuthRegisterOutputBodyAlias AuthRegisterOutputBody
	var decoded AuthRegisterOutputBodyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = AuthRegisterOutputBody(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"node"}); err != nil {
		return err
	}
	return nil
}

// NewAuthRegisterOutputBody returns a validated AuthRegisterOutputBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAuthRegisterOutputBody(fields AuthRegisterOutputBody) (*AuthRegisterOutputBody, error) {
	return ConstructModel(fields)
}

// AuthRegisterRequestBody Typed representation of the `AuthRegisterRequestBody` API schema.
type AuthRegisterRequestBody struct {
	// AuthId Optional `string` value serialized in the `authId` wire field.
	AuthId *string `json:"authId,omitempty"`
	// User Optional `string` value serialized in the `user` wire field.
	User *string `json:"user,omitempty"`
}

// NewAuthRegisterRequestBody returns a validated AuthRegisterRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAuthRegisterRequestBody(fields AuthRegisterRequestBody) (*AuthRegisterRequestBody, error) {
	return ConstructModel(fields)
}

// AuthRejectOutputBody Typed representation of the `AuthRejectOutputBody` API schema.
type AuthRejectOutputBody struct {
}

// AuthRejectRequestBody Typed representation of the `AuthRejectRequestBody` API schema.
type AuthRejectRequestBody struct {
	// AuthId Optional `string` value serialized in the `authId` wire field.
	AuthId *string `json:"authId,omitempty"`
}

// NewAuthRejectRequestBody returns a validated AuthRejectRequestBody built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewAuthRejectRequestBody(fields AuthRejectRequestBody) (*AuthRejectRequestBody, error) {
	return ConstructModel(fields)
}
