// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"bytes"
	"encoding/json"
)

// ErrorDetail Typed representation of the `ErrorDetail` API schema.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`
	// Message Error message text
	Message *string `json:"message,omitempty"`
	// Value The value at the given location
	Value any `json:"value,omitempty"`
}

// NewErrorDetail returns a validated ErrorDetail built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewErrorDetail(fields ErrorDetail) (*ErrorDetail, error) {
	return ConstructModel(fields)
}

// ErrorModel Typed representation of the `ErrorModel` API schema.
type ErrorModel struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`
	// Errors Optional list of individual error details
	Errors *NullableValue[[]ErrorDetail] `json:"errors,omitempty"`
	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`
	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`
	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`
	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

func (value *ErrorModel) UnmarshalJSON(data []byte) error {
	type ErrorModelAlias ErrorModel
	var decoded ErrorModelAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ErrorModel(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if value.Instance != nil {
		if err := ValidateUri("instance", *value.Instance); err != nil {
			return err
		}
	}
	if value.Type != nil {
		if err := ValidateUri("type", *value.Type); err != nil {
			return err
		}
	}
	if raw, ok := rawFields["errors"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		value.Errors = &NullableValue[[]ErrorDetail]{}
	}
	return nil
}

// NewErrorModel returns a validated ErrorModel built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewErrorModel(fields ErrorModel) (*ErrorModel, error) {
	return ConstructModel(fields)
}

// Node Typed representation of the `Node` API schema.
type Node struct {
	// ApprovedRoutes Required array value serialized in the `approvedRoutes` wire field.
	ApprovedRoutes []string `json:"approvedRoutes"`
	// AvailableRoutes Required array value serialized in the `availableRoutes` wire field.
	AvailableRoutes []string `json:"availableRoutes"`
	// CreatedAt Required `date-time`-formatted value serialized in the `createdAt` wire field.
	CreatedAt string `json:"createdAt"`
	// DiscoKey Required `string` value serialized in the `discoKey` wire field.
	DiscoKey string `json:"discoKey"`
	// Expiry Required `date-time`-formatted value serialized in the `expiry` wire field.
	Expiry NullableValue[string] `json:"expiry"`
	// GivenName Required `string` value serialized in the `givenName` wire field.
	GivenName string `json:"givenName"`
	// Id Required `uint64`-formatted value serialized in the `id` wire field.
	Id string `json:"id"`
	// IpAddresses Required array value serialized in the `ipAddresses` wire field.
	IpAddresses []string `json:"ipAddresses"`
	// LastSeen Required `date-time`-formatted value serialized in the `lastSeen` wire field.
	LastSeen NullableValue[string] `json:"lastSeen"`
	// MachineKey Required `string` value serialized in the `machineKey` wire field.
	MachineKey string `json:"machineKey"`
	// Name Required `string` value serialized in the `name` wire field.
	Name string `json:"name"`
	// NodeKey Required `string` value serialized in the `nodeKey` wire field.
	NodeKey string `json:"nodeKey"`
	// Online Required `boolean` value serialized in the `online` wire field.
	Online bool `json:"online"`
	// PreAuthKey Required object value serialized in the `preAuthKey` wire field.
	PreAuthKey NodePreAuthKey `json:"preAuthKey"`
	// RegisterMethod Required enumerated value serialized in the `registerMethod` wire field.
	RegisterMethod NodeRegisterMethodEnum `json:"registerMethod"`
	// SubnetRoutes Required array value serialized in the `subnetRoutes` wire field.
	SubnetRoutes []string `json:"subnetRoutes"`
	// Tags Required array value serialized in the `tags` wire field.
	Tags []string `json:"tags"`
	// User Required object value serialized in the `user` wire field.
	User User `json:"user"`
}

func (value *Node) UnmarshalJSON(data []byte) error {
	type NodeAlias Node
	var decoded NodeAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = Node(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id", "machineKey", "nodeKey", "discoKey", "ipAddresses", "name", "user", "lastSeen", "expiry", "preAuthKey", "createdAt", "registerMethod", "givenName", "online", "approvedRoutes", "availableRoutes", "subnetRoutes", "tags"}); err != nil {
		return err
	}
	if err := ValidateDateTime("createdAt", value.CreatedAt); err != nil {
		return err
	}
	if err := ValidateEnum("registerMethod", value.RegisterMethod, []NodeRegisterMethodEnum{"REGISTER_METHOD_UNSPECIFIED", "REGISTER_METHOD_AUTH_KEY", "REGISTER_METHOD_CLI", "REGISTER_METHOD_OIDC"}); err != nil {
		return err
	}
	return nil
}

// NewNode returns a validated Node built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewNode(fields Node) (*Node, error) {
	return ConstructModel(fields)
}

// NodeRegisterMethodEnum Required enumerated value serialized in the `registerMethod` wire field.
type NodeRegisterMethodEnum string

const (
	NodeRegisterMethodEnumRegisterMethodUnspecified NodeRegisterMethodEnum = "REGISTER_METHOD_UNSPECIFIED"
	NodeRegisterMethodEnumRegisterMethodAuthKey     NodeRegisterMethodEnum = "REGISTER_METHOD_AUTH_KEY"
	NodeRegisterMethodEnumRegisterMethodCli         NodeRegisterMethodEnum = "REGISTER_METHOD_CLI"
	NodeRegisterMethodEnumRegisterMethodOidc        NodeRegisterMethodEnum = "REGISTER_METHOD_OIDC"
)

// NodePreAuthKey Typed representation of the `NodePreAuthKey` API schema.
type NodePreAuthKey struct {
	// AclTags Required array value serialized in the `aclTags` wire field.
	AclTags []string `json:"aclTags"`
	// CreatedAt Required `date-time`-formatted value serialized in the `createdAt` wire field.
	CreatedAt NullableValue[string] `json:"createdAt"`
	// Ephemeral Required `boolean` value serialized in the `ephemeral` wire field.
	Ephemeral bool `json:"ephemeral"`
	// Expiration Required `date-time`-formatted value serialized in the `expiration` wire field.
	Expiration NullableValue[string] `json:"expiration"`
	// Id Required `uint64`-formatted value serialized in the `id` wire field.
	Id string `json:"id"`
	// Key Required `string` value serialized in the `key` wire field.
	Key string `json:"key"`
	// Reusable Required `boolean` value serialized in the `reusable` wire field.
	Reusable bool `json:"reusable"`
	// Used Required `boolean` value serialized in the `used` wire field.
	Used bool `json:"used"`
	// User Required object value serialized in the `user` wire field.
	User User `json:"user"`
}

func (value *NodePreAuthKey) UnmarshalJSON(data []byte) error {
	type NodePreAuthKeyAlias NodePreAuthKey
	var decoded NodePreAuthKeyAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = NodePreAuthKey(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"user", "id", "key", "reusable", "ephemeral", "used", "expiration", "createdAt", "aclTags"}); err != nil {
		return err
	}
	return nil
}

// NewNodePreAuthKey returns a validated NodePreAuthKey built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewNodePreAuthKey(fields NodePreAuthKey) (*NodePreAuthKey, error) {
	return ConstructModel(fields)
}

// User Typed representation of the `User` API schema.
type User struct {
	// CreatedAt Required `date-time`-formatted value serialized in the `createdAt` wire field.
	CreatedAt string `json:"createdAt"`
	// DisplayName Required `string` value serialized in the `displayName` wire field.
	DisplayName string `json:"displayName"`
	// Email Required `string` value serialized in the `email` wire field.
	Email string `json:"email"`
	// Id Required `uint64`-formatted value serialized in the `id` wire field.
	Id string `json:"id"`
	// Name Required `string` value serialized in the `name` wire field.
	Name string `json:"name"`
	// ProfilePicUrl Required `string` value serialized in the `profilePicUrl` wire field.
	ProfilePicUrl string `json:"profilePicUrl"`
	// Provider Required `string` value serialized in the `provider` wire field.
	Provider string `json:"provider"`
	// ProviderId Required `string` value serialized in the `providerId` wire field.
	ProviderId string `json:"providerId"`
}

func (value *User) UnmarshalJSON(data []byte) error {
	type UserAlias User
	var decoded UserAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = User(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if err := ValidateRequired(rawFields, []string{"id", "name", "createdAt", "displayName", "email", "providerId", "provider", "profilePicUrl"}); err != nil {
		return err
	}
	if err := ValidateDateTime("createdAt", value.CreatedAt); err != nil {
		return err
	}
	return nil
}

// NewUser returns a validated User built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewUser(fields User) (*User, error) {
	return ConstructModel(fields)
}
