// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"fmt"
)

type DebugCreateNodeParams struct {
	Key    *string
	Name   *string
	Routes *NullableValue[[]string]
	User   *string
}

// DebugCreateNode creates a node for debugging purposes. Provide `name` and `user` to describe the node, and use `key` or `routes` when those values are needed for the test setup. The response contains the created node.
//
// Parameters:
//
//	key: Optional `string` value serialized in the `key` wire field.
//	name: Optional `string` value serialized in the `name` wire field.
//	routes: Optional array value serialized in the `routes` wire field.
//	user: Optional `string` value serialized in the `user` wire field.
func DebugCreateNode(ctx context.Context, clientConfig ClientConfig, params DebugCreateNodeParams, opts ...RequestOption) (*NodeOutputBody, error) {
	key := params.Key
	name := params.Name
	routes := params.Routes
	user := params.User

	resp, err := DoCfg[NodeOutputBody](ctx, &clientConfig, "POST", "/api/v1/debug/node", &RequestOpts{
		Body: map[string]any{
			"key":    key,
			"name":   name,
			"routes": routes,
			"user":   user,
		},
		OperationID: "DebugCreateNode",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type ListNodesParams struct {
	User *string
}

// ListNodes lists nodes managed by the service. Supply `user` to filter the results to nodes associated with that user; omit it to list nodes without a user filter.
func ListNodes(ctx context.Context, clientConfig ClientConfig, params ListNodesParams, opts ...RequestOption) (*ListNodesOutputBody, error) {
	user := params.User

	resp, err := DoCfg[ListNodesOutputBody](ctx, &clientConfig, "GET", "/api/v1/node", &RequestOpts{
		Query: map[string]any{
			"user": QueryValue{Value: user, Style: "form", Explode: false},
		},
		OperationID: "ListNodes",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type BackfillNodeIPsParams struct {
	Confirmed *bool
}

// BackfillNodeIPs backfills IP addresses for registered nodes. Use the `confirmed` query parameter to indicate whether to confirm the operation, and review the returned `changes` list to see what was updated.
func BackfillNodeIPs(ctx context.Context, clientConfig ClientConfig, params BackfillNodeIPsParams, opts ...RequestOption) (*BackfillNodeIPsOutputBody, error) {
	confirmed := params.Confirmed

	resp, err := DoCfg[BackfillNodeIPsOutputBody](ctx, &clientConfig, "POST", "/api/v1/node/backfillips", &RequestOpts{
		Query: map[string]any{
			"confirmed": QueryValue{Value: confirmed, Style: "form", Explode: false},
		},
		OperationID: "BackfillNodeIPs",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type RegisterNodeParams struct {
	User *string
	Key  *string
}

// RegisterNode registers a node and returns its node record. Use `user` to associate the node with a user and `key` to provide a registration key when needed.
func RegisterNode(ctx context.Context, clientConfig ClientConfig, params RegisterNodeParams, opts ...RequestOption) (*NodeOutputBody, error) {
	user := params.User
	key := params.Key

	resp, err := DoCfg[NodeOutputBody](ctx, &clientConfig, "POST", "/api/v1/node/register", &RequestOpts{
		Query: map[string]any{
			"user": QueryValue{Value: user, Style: "form", Explode: false},
			"key":  QueryValue{Value: key, Style: "form", Explode: false},
		},
		OperationID: "RegisterNode",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type DeleteNodeParams struct {
	NodeId string
}

// DeleteNode deletes a node identified by its ID. Supply `nodeId` as an unsigned 64-bit integer value to identify the node to remove.
func DeleteNode(ctx context.Context, clientConfig ClientConfig, params DeleteNodeParams, opts ...RequestOption) (*DeleteNodeOutputBody, error) {
	nodeId := params.NodeId

	resp, err := DoCfg[DeleteNodeOutputBody](ctx, &clientConfig, "DELETE", fmt.Sprintf("/api/v1/node/%s", EncodePathSegment(nodeId)), &RequestOpts{
		OperationID: "DeleteNode",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type GetNodeParams struct {
	NodeId string
}

// GetNode retrieves a node by its identifier. Supply `nodeId` as an unsigned 64-bit integer value to identify the node.
func GetNode(ctx context.Context, clientConfig ClientConfig, params GetNodeParams, opts ...RequestOption) (*NodeOutputBody, error) {
	nodeId := params.NodeId

	resp, err := DoCfg[NodeOutputBody](ctx, &clientConfig, "GET", fmt.Sprintf("/api/v1/node/%s", EncodePathSegment(nodeId)), &RequestOpts{
		OperationID: "GetNode",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type SetApprovedRoutesParams struct {
	NodeId string
	Routes *NullableValue[[]string]
}

// SetApprovedRoutes updates the approved routes for a node. Send the route values in the `routes` array to set which routes are approved for that node.
//
// Parameters:
//
//	routes: Optional array value serialized in the `routes` wire field.
func SetApprovedRoutes(ctx context.Context, clientConfig ClientConfig, params SetApprovedRoutesParams, opts ...RequestOption) (*NodeOutputBody, error) {
	nodeId := params.NodeId
	routes := params.Routes

	resp, err := DoCfg[NodeOutputBody](ctx, &clientConfig, "POST", fmt.Sprintf("/api/v1/node/%s/approve_routes", EncodePathSegment(nodeId)), &RequestOpts{
		Body: map[string]any{
			"routes": routes,
		},
		OperationID: "SetApprovedRoutes",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type ExpireNodeParams struct {
	NodeId        string
	DisableExpiry *bool
	Expiry        *string
}

// ExpireNode updates the expiry settings for a node. Supply `expiry` as an ISO 8601 date-time or use `disableExpiry` to specify whether expiry is disabled.
//
// Parameters:
//
//	disableExpiry: Optional `boolean` value serialized in the `disableExpiry`
//	wire field.
//	expiry: Optional `date-time`-formatted value serialized in the `expiry` wire
//	field.
func ExpireNode(ctx context.Context, clientConfig ClientConfig, params ExpireNodeParams, opts ...RequestOption) (*NodeOutputBody, error) {
	nodeId := params.NodeId
	disableExpiry := params.DisableExpiry
	expiry := params.Expiry

	if expiry != nil {
		if err := ValidateDateTime("expiry", *expiry); err != nil {
			return nil, err
		}
	}

	resp, err := DoCfg[NodeOutputBody](ctx, &clientConfig, "POST", fmt.Sprintf("/api/v1/node/%s/expire", EncodePathSegment(nodeId)), &RequestOpts{
		Body: map[string]any{
			"disableExpiry": disableExpiry,
			"expiry":        expiry,
		},
		OperationID: "ExpireNode",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type RenameNodeParams struct {
	NodeId  string
	NewName string
}

// RenameNode renames a node by setting its new name. Supply the node identifier and the new name in the path.
func RenameNode(ctx context.Context, clientConfig ClientConfig, params RenameNodeParams, opts ...RequestOption) (*NodeOutputBody, error) {
	nodeId := params.NodeId
	newName := params.NewName

	resp, err := DoCfg[NodeOutputBody](ctx, &clientConfig, "POST", fmt.Sprintf("/api/v1/node/%s/rename/%s", EncodePathSegment(nodeId), EncodePathSegment(newName)), &RequestOpts{
		OperationID: "RenameNode",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type SetTagsParams struct {
	NodeId string
	Tags   *NullableValue[[]string]
}

// SetTags sets the tags for a node. Send the tags as an array of strings in the request body.
//
// Parameters:
//
//	tags: Optional array value serialized in the `tags` wire field.
func SetTags(ctx context.Context, clientConfig ClientConfig, params SetTagsParams, opts ...RequestOption) (*NodeOutputBody, error) {
	nodeId := params.NodeId
	tags := params.Tags

	resp, err := DoCfg[NodeOutputBody](ctx, &clientConfig, "POST", fmt.Sprintf("/api/v1/node/%s/tags", EncodePathSegment(nodeId)), &RequestOpts{
		Body: map[string]any{
			"tags": tags,
		},
		OperationID: "SetTags",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
