// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// GetPolicy retrieves the current policy. The response includes the policy text and the time it was last updated.
func GetPolicy(ctx context.Context, clientConfig ClientConfig, opts ...RequestOption) (*PolicyResponseBody, error) {

	resp, err := DoCfg[PolicyResponseBody](ctx, &clientConfig, "GET", "/api/v1/policy", &RequestOpts{
		OperationID: "GetPolicy",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type SetPolicyParams struct {
	Policy *string
}

// SetPolicy replaces the current policy with the policy value supplied in the request body. Include the policy text in `policy`; the response provides the saved policy and its update time.
//
// Parameters:
//
//	policy: Optional `string` value serialized in the `policy` wire field.
func SetPolicy(ctx context.Context, clientConfig ClientConfig, params SetPolicyParams, opts ...RequestOption) (*PolicyResponseBody, error) {
	policy := params.Policy

	resp, err := DoCfg[PolicyResponseBody](ctx, &clientConfig, "PUT", "/api/v1/policy", &RequestOpts{
		Body: map[string]any{
			"policy": policy,
		},
		OperationID: "SetPolicy",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type CheckPolicyParams struct {
	Policy *string
}

// CheckPolicy validates a policy against the server's live users and nodes without saving it. Provide `policy` as a string when included; the request body is required.
//
// Validates the given policy against the server's live users and nodes without persisting it.
//
// Parameters:
//
//	policy: Optional `string` value serialized in the `policy` wire field.
func CheckPolicy(ctx context.Context, clientConfig ClientConfig, params CheckPolicyParams, opts ...RequestOption) (*CheckPolicyOutputBody, error) {
	policy := params.Policy

	resp, err := DoCfg[CheckPolicyOutputBody](ctx, &clientConfig, "POST", "/api/v1/policy/check", &RequestOpts{
		Body: map[string]any{
			"policy": policy,
		},
		OperationID: "CheckPolicy",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
