// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

type DeletePreAuthKeyParams struct {
	Id *string
}

// DeletePreAuthKey deletes a pre-auth key. Use the optional `id` query parameter to identify the key to delete; provide it as a uint64-formatted string when supplied.
func DeletePreAuthKey(ctx context.Context, clientConfig ClientConfig, params DeletePreAuthKeyParams, opts ...RequestOption) (*DeletePreAuthKeyOutputBody, error) {
	id := params.Id

	resp, err := DoCfg[DeletePreAuthKeyOutputBody](ctx, &clientConfig, "DELETE", "/api/v1/preauthkey", &RequestOpts{
		Query: map[string]any{
			"id": QueryValue{Value: id, Style: "form", Explode: false},
		},
		OperationID: "DeletePreAuthKey",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

// ListPreAuthKeys lists the pre-auth keys configured on the server. Use this operation to retrieve each key's user, key value, expiration, usage state, and ACL tags.
func ListPreAuthKeys(ctx context.Context, clientConfig ClientConfig, opts ...RequestOption) (*ListPreAuthKeysOutputBody, error) {

	resp, err := DoCfg[ListPreAuthKeysOutputBody](ctx, &clientConfig, "GET", "/api/v1/preauthkey", &RequestOpts{
		OperationID: "ListPreAuthKeys",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type CreatePreAuthKeyParams struct {
	AclTags    *NullableValue[[]string]
	Ephemeral  *bool
	Expiration *string
	Reusable   *bool
	User       *string
}

// CreatePreAuthKey creates a pre-auth key for a user. Configure the key with fields such as `user`, `expiration`, `reusable`, `ephemeral`, and `aclTags`; `user` is a uint64-formatted string and `expiration` is a date-time.
//
// Parameters:
//
//	aclTags: Optional array value serialized in the `aclTags` wire field.
//	ephemeral: Optional `boolean` value serialized in the `ephemeral` wire
//	field.
//	expiration: Optional `date-time`-formatted value serialized in the
//	`expiration` wire field.
//	reusable: Optional `boolean` value serialized in the `reusable` wire field.
//	user: Optional `uint64`-formatted value serialized in the `user` wire field.
func CreatePreAuthKey(ctx context.Context, clientConfig ClientConfig, params CreatePreAuthKeyParams, opts ...RequestOption) (*PreAuthKeyOutputBody, error) {
	aclTags := params.AclTags
	ephemeral := params.Ephemeral
	expiration := params.Expiration
	reusable := params.Reusable
	user := params.User

	if expiration != nil {
		if err := ValidateDateTime("expiration", *expiration); err != nil {
			return nil, err
		}
	}

	resp, err := DoCfg[PreAuthKeyOutputBody](ctx, &clientConfig, "POST", "/api/v1/preauthkey", &RequestOpts{
		Body: map[string]any{
			"aclTags":    aclTags,
			"ephemeral":  ephemeral,
			"expiration": expiration,
			"reusable":   reusable,
			"user":       user,
		},
		OperationID: "CreatePreAuthKey",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type ExpirePreAuthKeyParams struct {
	Id *string
}

// ExpirePreAuthKey expires a pre-auth key. Supply its identifier in the `id` field as a uint64-formatted string when specifying which key to expire.
//
// Parameters:
//
//	id: Optional `uint64`-formatted value serialized in the `id` wire field.
func ExpirePreAuthKey(ctx context.Context, clientConfig ClientConfig, params ExpirePreAuthKeyParams, opts ...RequestOption) (*ExpirePreAuthKeyOutputBody, error) {
	id := params.Id

	resp, err := DoCfg[ExpirePreAuthKeyOutputBody](ctx, &clientConfig, "POST", "/api/v1/preauthkey/expire", &RequestOpts{
		Body: map[string]any{
			"id": id,
		},
		OperationID: "ExpirePreAuthKey",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
