// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strings"
	"time"
)

// ValidateRequired rejects decoded objects that omit a required wire member.
func ValidateRequired(fields map[string]json.RawMessage, required []string) error {
	for _, field := range required {
		if _, ok := fields[field]; !ok {
			return &SdkValidationError{
				Field:   field,
				Code:    "required",
				Message: fmt.Sprintf("Missing required property '%s'", field),
			}
		}
	}
	return nil
}

// ValidateEnum returns SdkValidationError if value is not in allowed.
func ValidateEnum[T comparable](field string, value T, allowed []T) error {
	for _, a := range allowed {
		if a == value {
			return nil
		}
	}
	parts := make([]string, len(allowed))
	for i, a := range allowed {
		parts[i] = fmt.Sprintf("%v", a)
	}
	return &SdkValidationError{
		Field:   field,
		Code:    "enum",
		Message: fmt.Sprintf("Validation failed for '%s': must be one of %s", field, strings.Join(parts, ", ")),
	}
}

// ValidateUri enforces a parseable URI.
func ValidateUri(field, value string) error {
	u, err := url.Parse(value)
	if err != nil || u.Scheme == "" || u.Host == "" {
		return &SdkValidationError{Field: field, Code: "format:uri", Message: fmt.Sprintf("Validation failed for '%s': must be a valid URI", field)}
	}
	return nil
}

// ValidateDateTime enforces RFC-3339 / ISO-8601 date-time.
func ValidateDateTime(field, value string) error {
	if _, err := time.Parse(time.RFC3339, value); err != nil {
		return &SdkValidationError{Field: field, Code: "format:date-time", Message: fmt.Sprintf("Validation failed for '%s': must be a valid ISO 8601 date-time", field)}
	}
	return nil
}
