// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
)

// ClientAuthConfig holds explicit request headers and optional credentials.
type ClientAuthConfig struct {
	Bearer  string
	Headers map[string]string
}

// SdkAuthError reports that the selected authentication capability cannot
// satisfy an operation's declared security requirement.
type SdkAuthError struct {
	sdkErrorBase
	OperationID string
	Preference  string
	Message     string
}

func (e *SdkAuthError) Error() string { return e.Message }

var operationSecurity = map[string][][]string{
	"ListApiKeys":       [][]string{[]string{"bearer"}},
	"CreateApiKey":      [][]string{[]string{"bearer"}},
	"ExpireApiKey":      [][]string{[]string{"bearer"}},
	"DeleteApiKey":      [][]string{[]string{"bearer"}},
	"AuthApprove":       [][]string{[]string{"bearer"}},
	"AuthRegister":      [][]string{[]string{"bearer"}},
	"AuthReject":        [][]string{[]string{"bearer"}},
	"DebugCreateNode":   [][]string{[]string{"bearer"}},
	"Health":            [][]string{[]string{"bearer"}},
	"ListNodes":         [][]string{[]string{"bearer"}},
	"BackfillNodeIPs":   [][]string{[]string{"bearer"}},
	"RegisterNode":      [][]string{[]string{"bearer"}},
	"DeleteNode":        [][]string{[]string{"bearer"}},
	"GetNode":           [][]string{[]string{"bearer"}},
	"SetApprovedRoutes": [][]string{[]string{"bearer"}},
	"ExpireNode":        [][]string{[]string{"bearer"}},
	"RenameNode":        [][]string{[]string{"bearer"}},
	"SetTags":           [][]string{[]string{"bearer"}},
	"GetPolicy":         [][]string{[]string{"bearer"}},
	"SetPolicy":         [][]string{[]string{"bearer"}},
	"CheckPolicy":       [][]string{[]string{"bearer"}},
	"DeletePreAuthKey":  [][]string{[]string{"bearer"}},
	"ListPreAuthKeys":   [][]string{[]string{"bearer"}},
	"CreatePreAuthKey":  [][]string{[]string{"bearer"}},
	"ExpirePreAuthKey":  [][]string{[]string{"bearer"}},
	"ListUsers":         [][]string{[]string{"bearer"}},
	"CreateUser":        [][]string{[]string{"bearer"}},
	"DeleteUser":        [][]string{[]string{"bearer"}},
	"RenameUser":        [][]string{[]string{"bearer"}},
}

const defaultBaseURL = ""

// applyAuthScheme attaches one named scheme. Schema-wide credential branches
// skip absent optional values; selection-owned providers return typed failures
// when the operation cannot obtain the credential it requires.
func applyAuthScheme(ctx context.Context, cfg *ClientConfig, headers map[string]string, query map[string]any, name string) error {
	switch name {
	case "bearer":
		if cfg == nil || cfg.Auth == nil {
			return nil
		}
		if cfg.Auth.Bearer != "" {
			headers["Authorization"] = "Bearer " + cfg.Auth.Bearer
		}
	}
	return nil
}

// isBearerScheme reports whether a declared security scheme name is one
// the bearer selection can satisfy.
func isBearerScheme(name string) bool {
	switch name {
	case "bearer":
		return true
	default:
		return false
	}
}

// hasBearerCredential reports whether the configuration carries the
// credential a declared scheme name needs.
func hasBearerCredential(cfg *ClientConfig, name string) bool {
	if cfg == nil || cfg.Auth == nil {
		return false
	}
	switch name {
	case "bearer":
		return cfg.Auth.Bearer != ""
	default:
		return false
	}
}

// selectBearerRequirement returns the security alternative to apply: the
// first one whose every member is configured, and otherwise the first one the
// selection can satisfy at all.
func selectBearerRequirement(requirements [][]string, cfg *ClientConfig) ([]string, bool) {
	var fallback []string
	found := false
	for _, alternative := range requirements {
		compatible := true
		configured := true
		for _, name := range alternative {
			if !isBearerScheme(name) {
				compatible = false
				break
			}
			if !hasBearerCredential(cfg, name) {
				configured = false
			}
		}
		if !compatible {
			continue
		}
		if configured {
			return alternative, true
		}
		if !found {
			fallback = alternative
			found = true
		}
	}
	return fallback, found
}

// applyAuth attaches credentials to the outgoing request. Selection-aware
// modes validate the current operation before applying any scheme.
func applyAuth(ctx context.Context, cfg *ClientConfig, headers map[string]string, query map[string]any, operationID string) error {
	if security, known := operationSecurity[operationID]; known {
		if len(security) == 0 {
			return nil
		}
		selected, compatible := selectBearerRequirement(security, cfg)
		if !compatible {
			return &SdkAuthError{
				OperationID: operationID,
				Preference:  "bearer",
				Message:     "auth bearer cannot satisfy the security requirement for operation " + operationID,
			}
		}
		for _, name := range selected {
			if err := applyAuthScheme(ctx, cfg, headers, query, name); err != nil {
				return err
			}
		}
	}
	return nil

}
