// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"strings"
	"testing"
)

const bearerTestToken = "mF_9.B5f-4.1JqM"

func captureBearerAuthRequest(t *testing.T, auth *ClientAuthConfig) SdkRequest {
	t.Helper()
	var captured SdkRequest
	config := ClientConfig{
		BaseURL: "https://bearer-auth.test",
		Auth:    auth,
		Middleware: []Middleware{
			func(_ context.Context, req *SdkRequest, _ SdkNext) (*SdkRawResponse, error) {
				captured = *req
				return &SdkRawResponse{StatusCode: 204}, nil
			},
		},
	}
	Configure(&config)
	defer Configure(nil)
	if _, err := ListApiKeys(context.Background(), config); err != nil {
		t.Fatalf("authenticated request failed: %v", err)
	}
	return captured
}

func TestBearerAuthorizationHeaderIsTheOnlyCredentialLocation(t *testing.T) {
	request := captureBearerAuthRequest(t, &ClientAuthConfig{Bearer: bearerTestToken})
	if request.Headers["Authorization"] != "Bearer "+bearerTestToken {
		t.Fatalf("unexpected Authorization header: %q", request.Headers["Authorization"])
	}
	if len(request.Headers) != 1 || strings.Contains(request.URL, bearerTestToken) {
		t.Fatalf("the bearer token reached another request component: %#v", request)
	}
}

func TestBearerAbsentTokenSendsNoCredential(t *testing.T) {
	request := captureBearerAuthRequest(t, &ClientAuthConfig{})
	if _, present := request.Headers["Authorization"]; present {
		t.Fatalf("an unset token still sent a credential: %#v", request.Headers)
	}
}
