// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"fmt"
)

type ListUsersParams struct {
	Id    *string
	Name  *string
	Email *string
}

// ListUsers lists users, with optional filters for user identifier, name, or email. Supply `id` as a uint64-formatted string when filtering by identifier; `name` and `email` are string filters.
func ListUsers(ctx context.Context, clientConfig ClientConfig, params ListUsersParams, opts ...RequestOption) (*ListUsersOutputBody, error) {
	id := params.Id
	name := params.Name
	email := params.Email

	resp, err := DoCfg[ListUsersOutputBody](ctx, &clientConfig, "GET", "/api/v1/user", &RequestOpts{
		Query: map[string]any{
			"id":    QueryValue{Value: id, Style: "form", Explode: false},
			"name":  QueryValue{Value: name, Style: "form", Explode: false},
			"email": QueryValue{Value: email, Style: "form", Explode: false},
		},
		OperationID: "ListUsers",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type CreateUserParams struct {
	DisplayName *string
	Email       *string
	Name        *string
	PictureUrl  *string
}

// CreateUser creates a user record. You can provide `name`, `displayName`, `email`, and `pictureUrl`; all defined fields are strings and none is marked as required.
//
// Parameters:
//
//	displayName: Optional `string` value serialized in the `displayName` wire
//	field.
//	email: Optional `string` value serialized in the `email` wire field.
//	name: Optional `string` value serialized in the `name` wire field.
//	pictureUrl: Optional `string` value serialized in the `pictureUrl` wire
//	field.
func CreateUser(ctx context.Context, clientConfig ClientConfig, params CreateUserParams, opts ...RequestOption) (*UserOutputBody, error) {
	displayName := params.DisplayName
	email := params.Email
	name := params.Name
	pictureUrl := params.PictureUrl

	resp, err := DoCfg[UserOutputBody](ctx, &clientConfig, "POST", "/api/v1/user", &RequestOpts{
		Body: map[string]any{
			"displayName": displayName,
			"email":       email,
			"name":        name,
			"pictureUrl":  pictureUrl,
		},
		OperationID: "CreateUser",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type DeleteUserParams struct {
	Id string
}

// DeleteUser deletes a user by identifier. Provide the user's `id` as a uint64-formatted string in the path.
func DeleteUser(ctx context.Context, clientConfig ClientConfig, params DeleteUserParams, opts ...RequestOption) (*DeleteUserOutputBody, error) {
	id := params.Id

	resp, err := DoCfg[DeleteUserOutputBody](ctx, &clientConfig, "DELETE", fmt.Sprintf("/api/v1/user/%s", EncodePathSegment(id)), &RequestOpts{
		OperationID: "DeleteUser",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type RenameUserParams struct {
	OldId   string
	NewName string
}

// RenameUser renames a user by changing the name associated with the specified identifier. Provide `oldId` as a uint64-formatted string and `newName` as a string in the path.
func RenameUser(ctx context.Context, clientConfig ClientConfig, params RenameUserParams, opts ...RequestOption) (*UserOutputBody, error) {
	oldId := params.OldId
	newName := params.NewName

	resp, err := DoCfg[UserOutputBody](ctx, &clientConfig, "POST", fmt.Sprintf("/api/v1/user/%s/rename/%s", EncodePathSegment(oldId), EncodePathSegment(newName)), &RequestOpts{
		OperationID: "RenameUser",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
